# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='budget',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
