# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_remove_choice_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Post'),
        ),
    ]
